Updated configs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,6 +7,17 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Define SSH Host
+          command: |
+            echo 'export SSH_HOST="default_IP"' >> $BASH_ENV  # Default IP or error handling
+            if [ "${CIRCLE_BRANCH}" == "production" ]; then
+              echo 'export SSH_HOST="13.235.186.84"' >> $BASH_ENV
+            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
+              echo 'export SSH_HOST="15.206.61.168"' >> $BASH_ENV
+            elif [ "${CIRCLE_BRANCH}" == "new" ]; then
+              echo 'export SSH_HOST="3.111.35.110"' >> $BASH_ENV
+            fi
+      - run:
           name: Notify Slack - Deployment Started
           command: |
             BRANCH=$(git rev-parse --abbrev-ref HEAD)
@@ -28,19 +39,8 @@ jobs:
           name: SSH to EC2 and Deploy
           command: |
             set +e
-            SSH_HOST=""
-            if [ "${CIRCLE_BRANCH}" == "production" ]; then
-              SSH_HOST="13.235.186.84"
-            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
-              SSH_HOST="15.206.61.168"
-            elif [ "${CIRCLE_BRANCH}" == "new" ]; then
-              SSH_HOST="3.111.35.110"
-            fi
             ssh -o StrictHostKeyChecking=no root@$SSH_HOST "bash /root/toolplate-backend/deploy.sh > /root/toolplate-backend/deploy_output.txt 2>&1"
-            EXIT_STATUS=$?
-            if [ $EXIT_STATUS -ne 0 ]; then
-              echo "Deployment script failed with status $EXIT_STATUS" > deploy_output.txt
-            fi
+            echo "export EXIT_STATUS=$?" >> $BASH_ENV
             set -e
       - run:
           name: Download deploy_output.txt
@@ -50,7 +50,7 @@ jobs:
           command: |
             DEPLOY_OUTPUT=$(cat deploy_output.txt || echo "Deployment failed, no output found.")
             STATUS_COLOR="#EF4444"
-            if [ $EXIT_STATUS -eq 0 ]; then
+            if [ "${EXIT_STATUS}" -eq 0 ]; then
               STATUS_COLOR="#47BC63"
               TITLE="✅ Deployment Succeeded!"
             else
